-- AlterTable
ALTER TABLE `finallevel` ADD COLUMN `description` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `image` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `subTitlte` VARCHAR(191) NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `sublevel` ADD COLUMN `description` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `image` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `subTitlte` VARCHAR(191) NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `subsublevel` ADD COLUMN `description` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `image` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `subTitlte` VARCHAR(191) NOT NULL DEFAULT '';
