-- AlterTable
ALTER TABLE `level` ADD COLUMN `description` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `image` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `subTitlte` VARCHAR(191) NOT NULL DEFAULT '';
